### ISSUE TITLE
DomainNet Dataset config is missing

### ISSUE THREAD

**Issue by daiqing7** [lisadunlap/LADS#12]
When I tried to runexperiments with DomainNet dataset, I got the error:

DomainNet Dataset config is not found in data_configs/.

Can you upload the data config for domain net? Thanks

**Comment by lisadunlap** [comment]
of course, the repo should be updated later today!

**Comment by lisadunlap** [comment]
fixed! Merge is here: https://github.com/lisadunlap/LADS/pull/14 

Keep in mind our experiments are on a specific subset of DomainNet, you can run those by setting `DATA.DATASET=DomainNetMini`. I also uploaded the embeddings for CUB, DomainNetMini, and Waterbirds if you don't want to regenerate them

**Comment by daiqing7** [comment]
> fixed! Merge is here: #14
> 
> Keep in mind our experiments are on a specific subset of DomainNet, you can run those by setting `DATA.DATASET=DomainNetMini`. I also uploaded the embeddings for CUB, DomainNetMini, and Waterbirds if you don't want to regenerate them

Thanks for your help. But I still have some questions.

As you mentioned, experiments are on a specific subset of DomainNet. If I want to run, for instance, "real -> sketch" in DomainNet, what I should do?

If I run 'python main.py --config configs/DomainNet/lads.yaml',  why are there multiple TEXT_PROMPTS and NEUTRAL_TEXT_PROMPTS from multiple domains? From my understanding, NEUTRAL_TEXT_PROMPTS (source) should be 'real' and TEXT_PROMPTS (target) should be 'sketch'?

And in data_helpers.py:
`    elif dataset_name == "DomainNet":
        cfg = get_config('DomainNet')
        trainset = DomainNet('/project/sds-rise/daiqing/LADS/data', cfg, split='train', transform=transform)
        valset = DomainNet('/project/sds-rise/daiqing/LADS/data', cfgsplit='val', transform=val_transform)
        testset = DomainNet('/project/sds-rise/daiqing/LADS/data', cfg, split='test', transform=val_transform)
    elif dataset_name == "DomainNetMini":
        trainset = OneDomain('/project/sds-rise/daiqing/LADS/data', domain='sketch', split='train', transform=transform)
        valset = OneDomain('/project/sds-rise/daiqing/LADS/data', domain='sketch', split='val', transform=val_transform)
        testset = MultiDomain('/project/sds-rise/daiqing/LADS/data', domains=['clipart', 'painting', 'real'], split='test', transform=val_transform)`
        
     May I ask the differences between  "DomainNet" and  "DomainNetMini"? Do we get a chance to use  "DomainNet"? According to the paper, we seem to have only one source domain all the time, does it mean we actually will never set dataset_name == "DomainNet" in 'configs/DomainNet/lads.yaml'?
     
     Many thanks!
